# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.5-alpine
    restart: always
    volumes:
      - ./pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example